modelsproDairy/modelsapp/urls.py
from django.conf.urls import patterns, url

from django.conf.urls import url, include
from rest_framework import routers
from modelsapp import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'usersearch', views.UserSearchSet, base_name="users")

urlpatterns = patterns('modelsapp.views',
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^Contacts/api/subjects/$','getsubjectlist',name='getsubjectlist'),
    url(r'^Contacts/api/namesearchlist/$','namesearchlist',name='namesearchlist'),
    url(r'^Contacts/class/addsubject/$','addsubject',name='addsubject'),
    url(r'^Contacts/class/editsubject/$','editsubject',name='editsubject'),
    url(r'^Contacts/class/searchsubject/$','searchsubject',name='searchsubject'),
    url(r'^Contacts/class/subjecttodep/$','subjecttodep',name='subjecttodep'),
    url(r'^Contacts/class/addtest/$','addtest',name='addtest'),
    url(r'^Contacts/class/viewtest/$','viewtest',name='viewtest'),
    url(r'^Contacts/class/edittest/$','edittest',name='edittest'),
    url(r'^Contacts/class/reportcard/$','reportcard',name='reportcard'),
    url(r'^Contacts/admin/approveleave_form/$','approveleave_form',name='approveleave_form'),
    url(r'^Contacts/admin/addacademicyear/$','addacademicyear',name='addacademicyear'),
    url(r'^Contacts/admin/approveleaveform/(\d+)/$','approveleaveform',name='approveleaveform'),
    url(r'^Contacts/admin/approveleave/$', 'approveleave', name='approveleave'),
    url(r'^Contacts/applyleave/$', 'applyleaveform', name='applyleaveform'),
    url(r'^Contacts/admin/releaseleaves/$', 'releaseleaves', name='releaseleaves'),
    url(r'^Contacts/admin/skilltitleaddform/$', 'skilltitleaddform', name='skilltitleaddform'),
    url(r'^Contacts/admin/addholidayform/$', 'addholidayform', name='addholidayform'),
    url(r'^Contacts/admin/skillsearchform/$', 'skillsearchform', name='skillsearchform'),
    url(r'^Contacts/skillcontactaddform/$', 'skillcontactaddform', name='skillcontactaddform'),
    url(r'^Contacts/admin/contactform/$', 'contactform', name='contactform'),
    url(r'^Contacts/admin/jobtitleform/$', 'jobtitleform', name='jobtitleform'),
    url(r'^Contacts/admin/departmentform/$', 'departmentform', name='departmentform'),
    url(r'^Contacts/admin/supervisorform/$', 'supervisorform', name='supervisorform'),
    url(r'^Contacts/admin/esearchform/$', 'esearchform', name='esearchform'),
    url(r'^Contacts/admin/editsearchform/$', 'editsearchform', name='editsearchform'),
    url(r'^Contacts/admin/deletesearchform/$', 'deletesearchform', name='deletesearchform'),
    url(r'^Contacts/adminindex/$', 'adminindex', name='adminindex'),
    url(r'^Contacts/login/', 'login',name='login'),
    url(r'^Contacts/logout/','logout',name='logout'),
    url(r'^Contacts/viewcontact/(\d+)/$','viewcontact',name='viewcontact'),
    url(r'^Contacts/viewdepcontact/(\d+)/$','viewdepcontact',name='viewdepcontact'),
    url(r'^Contacts/viewdepsubject/(\d+)/$','viewdepsubject',name='viewdepsubject'),
    url(r'^Contacts/viewdeptest/(\d+)/$','viewdeptest',name='viewdeptest'),
    url(r'^Contacts/editcontact/(\d+)/$','editcontactform',name='editcontactform'),
    url(r'^Contacts/deletecontact/(\d+)/$','deletecontactform',name='deletecontactform'),
    #url(r'^Contacts/logout/', 'django.contrib.auth.logout'),
)

modelsproDairy/modelsproDairy/urls.py
#from django.conf.urls import patterns, include, url
#from django.contrib import admin

#urlpatterns = patterns('',
#    # Examples:
#    # url(r'^$', 'modelspro.views.home', name='home'),
#    # url(r'^blog/', include('blog.urls')),
#
#    url(r'^admin/', include(admin.site.urls)),
#)
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
urlpatterns = patterns('',
    (r'^', include('modelsapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modelsproDairy/modelsapp/models.py
from django.db import models
import datetime

# Create your models here.


class AcademicYear(models.Model):
    academic_year = models.CharField(max_length=30)
    current = models.BooleanField(default=False)
    #current = models.BooleanField()
    class Meta:
        unique_together = (("academic_year"),)

class Address(models.Model):
    H_No = models.CharField(max_length=30)
    Line1 = models.CharField(max_length=30)
    street = models.CharField(max_length=30)
    colony = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    pin = models.IntegerField()

class JobTitle(models.Model):
    title = models.CharField(max_length=30)
    class Meta:
        unique_together = (("title"),)

class Department(models.Model):
    dep_name=models.CharField(max_length=30)
    class_teacher_id = models.IntegerField(default=0)
    ac_year = models.ManyToManyField(AcademicYear)
    """
    from_year = models.IntegerField(default=int(datetime.datetime.today().year))
    to_year = models.IntegerField(default=int(datetime.datetime.today().year)+1)
    """
    """ # implemented department name duplication in view
    class Meta:
        #unique_together = (("dep_name","from_year","to_year"),)
        unique_together = (("dep_name"),)
    """
    def get_tests_number(self):
        test_obj_list = []
        test_name_list = []
        for con in self.contact_set.all():
            for test in con.test_set.all():
                test_name_list.append(test.test_name)
        return len(set(test_name_list))

class Subject(models.Model):
    sub_name=models.CharField(max_length=50)
    teacher_id = models.IntegerField(default=0)
    text_book=models.CharField(max_length=50)
    publisher=models.CharField(max_length=50)
    """
    from_year = models.IntegerField(default=int(datetime.datetime.today().year))
    to_year = models.IntegerField(default=int(datetime.datetime.today().year)+1)
    """
    ac_year = models.ManyToManyField(AcademicYear)
    department = models.ManyToManyField(Department)
    department_name=models.CharField(max_length=50, default="No deparment")
    """
    class Meta:
        #unique_together = (("sub_name","text_book","publisher","from_year","to_year", "department_name"),)
        unique_together = (("sub_name","text_book","publisher", "department_name"),)
    """


"""
class Department(models.Model):
    dep_name = models.CharField(max_length=30)
"""

class Supervisor(models.Model):
    sup_id = models.IntegerField()
    class Meta:
        unique_together = (("sup_id"),)

class Contact(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    sur_name = models.CharField(max_length=30)
    login_name = models.CharField(max_length=30,default="suser1")
    email = models.EmailField()
    emp_id = models.IntegerField()
    supervisor = models.ForeignKey(Supervisor)
    #department = models.ForeignKey(Department)
    department = models.ManyToManyField(Department)
    ac_year = models.ManyToManyField(AcademicYear)
    job_title = models.ForeignKey(JobTitle)
    phone = models.IntegerField()
#   picture = models.CharField(max_length=30)
    picture = models.FileField(upload_to='tmp/')
    address = models.OneToOneField(Address)
    class Meta:
        unique_together = (("first_name", "last_name", "sur_name"),)

class SkillTitle(models.Model):
    skill_title = models.CharField(max_length=30)
    class Meta:
        unique_together = (("skill_title"),)
    
class Skill(models.Model):
    skill_name = models.CharField(max_length=30)
    exp_years = models.IntegerField()
    exp_level = models.IntegerField()
    contact = models.ManyToManyField(Contact)

class Leave(models.Model):
    requester = models.ForeignKey(Contact)
    app_id = models.IntegerField(default=0)
    req_date = models.DateField(blank=False, default=datetime.datetime.now)
    app_date = models.DateField(blank=False, default=datetime.datetime.now)
    from_date = models.DateField(blank=False, default=datetime.datetime.now)
    to_date = models.DateField(blank=False, default=datetime.datetime.now)
    count = models.IntegerField(default=0)
    state = models.IntegerField(default=0)
    type = models.IntegerField(default=0)
    req_comment = models.CharField(max_length=250, default='-')
    app_comment = models.CharField(max_length=250, default='-')

class Holiday(models.Model):
    h_date = models.DateField()
    holiday_name = models.CharField(max_length=50)

class LeaveBalance(models.Model):
    contact = models.OneToOneField(Contact)
    sick_leave_balance = models.IntegerField(default=0)
    earned_leave_balance = models.IntegerField(default=0)

class Test(models.Model):
    test_name=models.CharField(max_length=50)
    marks = models.IntegerField(default=0)
    grade=models.CharField(max_length=50)
    comment=models.CharField(max_length=500)
    academic_year = models.ManyToManyField(AcademicYear)
    subject = models.ManyToManyField(Subject)
    contact = models.ManyToManyField(Contact)

modelsproDairy/modelsapp/forms.py
# -*- coding: utf-8 -*-
from django import forms

class ESearchForm(forms.Form):
    search_key=forms.CharField(help_text ='max.30 characters')

class JobTitleForm(forms.Form):
    title=forms.CharField(help_text ='max.30 characters')

class AddAcademicYearForm(forms.Form):
    academic_year=forms.CharField(help_text ='max.30 characters')

class DepartmentForm(forms.Form):
    dep_name=forms.CharField(help_text ='max.30 characters')
    """
    from_year=forms.IntegerField()
    to_year=forms.IntegerField()
    """
    class_teacher_id=forms.IntegerField()

class SupervisorForm(forms.Form):
    sup_id=forms.IntegerField()

class ViewContactForm(forms.Form):
    con_id=forms.IntegerField()

class SkillTitleForm(forms.Form):
    skill_title=forms.CharField(help_text ='max.30 characters')
    #skill_title=forms.CharField()

class ContactForm(forms.Form):
    picture = forms.FileField(
        label='Contact Picture',
        help_text='max. 42 megabytes'
    )
    c_id=forms.IntegerField(required=False)
    old_pic=forms.CharField(required=False)
    first_name=forms.CharField(help_text ='max.30 characters')
    last_name=forms.CharField(help_text ='max.30 characters')
    sur_name=forms.CharField(help_text ='max.30 characters')
    log_name=forms.CharField(help_text ='max.10 characters')
    email=forms.EmailField(help_text ='max.30 characters')
    emp_id=forms.IntegerField()
    phone=forms.IntegerField()
    H_No = forms.CharField()
    Line1 = forms.CharField()
    street = forms.CharField()
    colony = forms.CharField()
    city = forms.CharField()
    pin = forms.IntegerField()

class SubjectForm(forms.Form):
    sub_name=forms.CharField(help_text ='max.50 characters')
    text_book=forms.CharField(help_text ='max.50 characters')
    publisher=forms.CharField(help_text ='max.50 characters')
    teacher_id=forms.IntegerField()
    """
    from_year=forms.IntegerField()
    to_year=forms.IntegerField()
    """ 
   

modelsproDairy/modelsapp/templates/jinja2/adminindex.jinja
<!DOCTYPE html>
{% include 'header.jinja' %}
<section>
   <div class="row">
      <!--<div class="col-sm-2" style="background-color:lavender;">
         <table class="table table-striped table-bordered" style=" margin-bottom: 0px;margin-bottom: 0px;height: 302px;width: 222px;width=222px; margin-bottom: 0px">
         {% if user.is_superuser %}
         <tr><td><a href="/Contacts/admin/contactform" style = "font-size:15px">Add Contact</a></td></tr>
         <tr><td><a href="/Contacts/admin/jobtitleform">JobTitle Add Form</a></td></tr>
         <tr><td><a href="/Contacts/admin/departmentform">Department Add Form</a></td></tr>
         <tr><td><a href="/Contacts/admin/supervisorform">Supervisor Add Form</a></td></tr>
         <tr><td><a href="/Contacts/admin/editsearchform">Edit Contact</a></td></tr>
         <tr><td><a href="/Contacts/admin/deletesearchform">Delete Contact</a></td></tr>
         <tr><td><a href="/Contacts/admin/skilltitleaddform">Skill Add</a></td></tr>
         <tr><td><a href="/Contacts/admin/skillsearchform">Skill Search Add</a></li></td></tr>
         <tr><td><a href="/Contacts/admin/addholidayform">Add Holiday</a></li></td></tr>
         <tr><td><a href="/Contacts/admin/releaseleaves">Release Leaves</a></li></td></tr>
         <tr><td><a href="/Contacts/admin/approveleave">Approve Leave</a></td></tr>
         {% endif %}
         <tr><td><a href="/Contacts/admin/esearchform">Contact Search</a></td></tr>
         <tr><td><a href="/Contacts/applyleave">Apply Leave</a></li></td></tr>
         <tr><td><a href="/Contacts/skillcontactaddform">Skill Contact Add</a></li></td></tr>
         <tr><td><a href="/Contacts/logout">Logout</a></li></td></tr>
         </table>
         </div>-->
      <div class="col-sm-12" >
         <!--<p class= "lead" style="font-size:15px">
            Search Contact <br>
            To Search Contact in the web contacts
         </p>-->
         {% if user.is_superuser %}
      <div class="table-responsive" >
         <table class="table table-striped table-bordered" >
            <thead>
               <tr><th style="width:40%">Department</th><th style="width:20%">Students</th><th style="width:20%"> Subjects</th><th style="width:20%">Tests</th>
               </tr>
            </thead>
               {% if ay %}
                  {% for dep in ay.department_set.all() %}
                     <tr><td>{{ dep.dep_name }}</td><td><a href="/Contacts/viewdepcontact/{{dep.id}}"> {{dep.contact_set.all()|count}}</a></td><td><a href="/Contacts/viewdepsubject/{{dep.id}}">{{dep.subject_set.all()|count}}</a></td><td><a href="/Contacts/viewdeptest/{{dep.id}}"> {{dep.get_tests_number()}}</a></td></tr>
                  {% endfor %}
               {% endif %}
            <tbody>
            </tbody>
          </table>
      </div>
         <!--<a>Add Contact</a>
         <p>
            <a> To Add Contact to the web contacts<a>
         </p>
         <a>JobTitle Add</a>
         <p>
            <a> To Add JobTitle in the web contacts<a>
         </p>
         <a>Department Add</a>
         <p>
            <a> To Add Department in the web contacts<a>
         </p>
         <a>Supervisor Add</a>
         <p>
            <a> To Add Supervisor Contact in the web contacts<a>
         </p>
         <a>Edit Contact</a>
         <p>
            <a> To Edit Contact in the web contacts<a>
         </p>
         <a>Delete Contact</a>
         <p>
            <a> To delete Contact from the web contacts<a>
         </p>-->
         {% endif %}
      </div>
   </div>
</section>
{% include 'footer.jinja' %}

modelsproDairy/modelsapp/templates/jinja2/edittest.jinja
{% include 'header.jinja' %}
<h4>{{ msg }}</h4>
<form action="{{ url('viewtest') }}"  method="post" enctype="multipart/form-data">
   <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
   <input type="hidden" name="edit_test" value="">
   <input type="hidden" name="{{te_name}}^{{subt.id}}^{{dept.id}}" value="">    
   <table class="table table-striped table-bordered">
      <thead>
         <tr>
            <th>Contact</th>
            <th>Marks</th>
            <th>Grade</th>
            <th>Comments</th>
         <tr>
      </thead>
      <tbody>
         <h4>Department {{dept.dep_name}}</h4>
         <h4>Subject {{subt.sub_name}}</h4>
         <h4>Test {{te_name}}</h4>
         {% if dept and subt %}
         {% for con in dept.contact_set.all() %}
         <tr>
            <td>{{con.sur_name}},{{con.first_name}}</td>
            {% for tes in ay.test_set.filter(test_name = te_name, subject = subt, contact = con) %}
            <td><input type="text" name="{{tes.test_name}}^{{subt.id}}^{{con.id}}^marks" value="{{tes.marks}}"></td>
            <td><input type="text" name="{{tes.test_name}}^{{subt.id}}^{{con.id}}^grade" value="{{tes.grade}}"></td>
            <td><input type="text" name="{{tes.test_name}}^{{subt.id}}^{{con.id}}^comment" value="{{tes.comment}}"></td>
            {% endfor %}
         </tr>
         {% endfor %}
         {% endif %}
      </tbody>
   </table>
   <input type="submit" value="Save">
</form>
{% include 'footer.jinja' %}

modelsproDairy/modelsapp/templates/jinja2/edittest_new.jinja
{% include 'header.jinja' %}
<h4>{{ msg }}</h4>
{% include 'footer.jinja' %}

modelsproDairy/modelsapp/templates/jinja2/footer.jinja
<footer>
Copyright © WebDairy
</footer>
</body>
</html>

modelsproDairy/modelsapp/templates/jinja2/login.jinja
<!DOCTYPE html>
{% include 'header.jinja' %}
<section>
<!--<center><div class="table-responsive" >
<table><tr><td>Username:</td><td><input type="text" name="username" id="username" placeholder="Username"></td><td>Password:</td><td><input type="password" name= "password" id="password" placeholder="Password"></td><td><button type="submit" class="btn btn-default" style="width:50px;height:35px;margin-top:0px;">Login</button></td><tr></table>
</div></center>-->
   <div style="margin-left:20%;margin-right:20%">
      <form action="/Contacts/adminindex/" method="post">
         <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
         
         
         <div class="form-group">
            <label for="email" class="col-sm-2">Username:</label>
            <input type="text" class="col-sm-2" name="username" id="username" placeholder="Username"></br>
         </div>
         <div class="form-group">
            <label for="pwd" class="col-sm-2" >Password:</label>
            <input type="password" class=" col-sm-2" name= "password" id="password" placeholder="Password"></br>
         </div>
         <!--<button type="submit" class="btn btn-default" style="width:50px;height:35px;margin-top:0px;">Login</button>-->
         <button type="submit" style="height:30px" >Login</button>
         
      </form>
   </div>
</section>
<section>

   <div class="table-responsive" style="margin-left:20%;margin-right:20%">
         <table class="table table-striped table-bordered" >
            <thead>
               <tr>
               </tr>
            </thead>
            <tbody>
               <tr><td>Academic Year</td><td>{{ay.academic_year}}</td><tr>
               <tr><td>Departments</td><td>{{ ay.department_set.all()| count }}</td><tr>
               <tr><td>Subjects</td><td>{{ay.subject_set.all() | count}}</td><tr>
               <tr><td>Students</td><td>{{ ay.contact_set.filter(job_title__title = "Student") | count}}</td><tr>
               <tr><td>Teaching Staff</td><td>{{ay.contact_set.filter(job_title__title = "Teacher") | count}}</td><tr>
               <tr><td>Non-Teaching Staff</td><td>{{ay.contact_set.filter(job_title__title = "NTStaff") | count}}</td><tr>
               <tr><td>Skills</td><td>0</td><tr>
               <tr><td>Tests</td><td>{{ay.test_set.all() | count}}</td><tr>
               <tr><td>Holidays</td><td>0</td><tr>
               <tr><td>Leaves</td><td>0</td><tr>
            </tbody>
         </table>
   </div>          

</section>
{% include 'footer.jinja' %}

modelsproDairy/modelsapp/templates/jinja2/reportcard.jinja
{% include 'header.jinja' %}
<!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>-->

<h4>{{ msg }}</h4>
<h2> Report Card </h2>
<form action="{{ url('reportcard') }}"  method="post" enctype="multipart/form-data">
<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
<select name="contact_id">
   {%for con in contact_list %}                
   <option value="{{con.id}}" >{{con.sur_name}},{{con.first_name}} </option>
   {% endfor %}
</select>
<input type=submit value="Submit">
<form>
{% if cont %}
<h3> {{cont.sur_name}},{{cont.first_name}} </h3>

{% if test_list %}
{% if department %}
<h4> {{department.dep_name }}</h4>
<!--<div class="panel panel-default" style="width: 100%; padding: 10px; margin: 10px">
        <div id="Tabs" role="tabpanel">-->
<div class="tabbable">
<ul class="nav nav-tabs">
{% for te_name in test_list %}
<!--<h4> {{te_name}} </h4>-->
 {% if te_name == test_list[-1] %}
 <li class="active"><a href="#{{te_name}}" data-toggle="tab">{{te_name}}</a></li>
 {% else %}
   <li><a href="#{{te_name}}" data-toggle="tab">{{te_name}}</a></li>
 {% endif %}

{% endfor %}
</ul>
<div class="tab-content" >
{% for te_name in test_list %}
<!--<h4> {{te_name}} </h4>-->
<!--<div role="tabpanel" class="tab-pane active" id="{{te_name}}">-->
{% if te_name == test_list[-1] %}
<div class="tab-pane active" id="{{te_name}}">
{% else %}
<div class="tab-pane" id="{{te_name}}">
{% endif %}
<table class="table table-striped table-bordered">
   <thead><tr>
      <th>Subject</th>
      <th>Marks</th>
      <th>Grade</th>
      <th>Comment</th></tr>
   <thead>
   <tbody>
      {% for sub in department.subject_set.all() %}
      {% for test in cont.test_set.filter(test_name = te_name, subject = sub) %}
      <tr>
         <td>{{sub.sub_name}}</td>
         <td>{{test.marks}}</td>
         <td>{{test.grade}}</td>
         <td>{{test.comment}}</td>
      </tr>
      {% endfor %}
      {% endfor %}
   </tbody>
</table>
</div>
{% endfor %}
</div>
<!--</div>
</div>-->
</div>
{% endif %}
{% endif %}
{% endif %}
{% include 'footer.jinja' %}

modelsproDairy/modelsapp/templates/jinja2/viewdepcontact.jinja
<!DOCTYPE html>
{% include 'header.jinja' %}
<h2> Department "{{department.dep_name}}" Members</h2>
<section>
   <div class="row">

      <div class="col-sm-12" >
         {% if user.is_superuser %}
      <div class="table-responsive" >
         <table class="table table-striped table-bordered" >
            <thead>
               <tr><th style="width:10%">ID</th><th style="width:20%">First Name</th><th style="width:20%">Last Name</th><th style="width:20%"> SurName</th><th style="width:15%">Email</th><th style="width:15%">Phone</th>
               </tr>
            </thead>
               {% if department %}
                  {% for con in department.contact_set.all() %}
                     <tr><td><a href="/Contacts/viewcontact/{{con.id}}">{{ con.id }}</a></td><td> {{con.first_name}}</td><td>{{con.last_name}}</td><td> {{con.sur_name}}</td><td>{{con.email}}</td><td>{{con.phone}}</td></tr>
                  {% endfor %}
               {% endif %}
            <tbody>
            </tbody>
          </table>
      </div>
         {% endif %}
      </div>
   </div>
</section>
{% include 'footer.jinja' %}

modelsproDairy/modelsapp/templates/jinja2/viewdepsubject.jinja
<!DOCTYPE html>
{% include 'header.jinja' %}
<h2> Department "{{department.dep_name}}" Subjects </h2>
<section>
   <div class="row">
      <div class="col-sm-12" >
         {% if user.is_superuser %}
      <div class="table-responsive" >
         <table class="table table-striped table-bordered" >
            <thead>
               <tr><th style="width:10%">Teacher ID</th><th style="width:30%">Subject Name</th><th style="width:30%">Text Book</th><th style="width:30%"> Publisher </th></tr>
            </thead>
               {% if department %}
                  {% for sub in department.subject_set.all() %}
                     <tr><td><a href="/Contacts/viewcontact/{{sub.teacher_id}}">{{ sub.teacher_id }}</a></td><td> {{sub.sub_name}}</td><td>{{sub.text_book}}</td><td>{{sub.publisher}}</td></tr>
                  {% endfor %}
               {% endif %}
            <tbody>
            </tbody>
          </table>
      </div>
         {% endif %}
      </div>
   </div>
</section>
{% include 'footer.jinja' %}

modelsproDairy/modelsapp/templates/jinja2/viewtest.jinja
{% include 'header.jinja' %}
<h4>{{ msg }}</h4>
<form action="{{ url('viewtest') }}"  method="post" enctype="multipart/form-data">
   <div class="form-group">
      <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
      <div class="col-sm-6" >
      <p> Test list </p>
      <select name="test">
         {% for test in t_list %}
         <option value="{{test}}" >{{test}} </option>
         {% endfor %}
      </select>
      </div>
      <div class="col-sm-6" >
      <p> Department list </p>
      <select name="department">
         {% for dep in d_list %}
         <option value="{{dep.id}}" >{{dep.dep_name}} </option>
         {% endfor %}
      </select>
      </div>
      <p><input type=submit value="Submit"></p>
   </div>
</form>
{% if department %}
<h4>Department {{department.dep_name}}</h4>
<h4>Test {{te_name}}</h4>
<table class="table table-striped table-bordered">
   <thead>
      <tr>
         <th>contact</th>
         {% for sub in department.subject_set.all()%}
         <th>{{ sub.sub_name }}</th>
         {% endfor %}
      </tr>
   </thead>
   <tbody>
      {% for con in department.contact_set.all() %}
      <tr>
         <td>{{con.sur_name}},{{con.first_name}}</td>
         {% for sub in department.subject_set.all()%}
         {% for tes in ay.test_set.filter(test_name = te_name, subject = sub, contact = con) %}
         <td>{{tes.marks}}</td>
         {% endfor %}
         {% endfor %}
      </tr>
      {% endfor %}
      <tr>
         <td></td>
         {% for sub in department.subject_set.all()%}
         <td>
            <form action="{{ url('edittest') }}"  method="post" enctype="multipart/form-data">
               <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
               <input type="hidden" name="{{te_name}}^{{sub.id}}^{{department.id}}" value="">
               <input type="submit" value="Edit">
            </form>
         </td>
         {% endfor %}
      </tr>
      {% endif %}
   </tbody>
</table>
{% include 'footer.jinja' %}

modelsproDairy/modelsapp/templates/jinja2/viewtest_orig.jinja
{% include 'header.jinja' %}
<h4>{{ msg }}</h4>
{% for dep in d_list %}
    {% for sub in dep.subject_set.all %}
        <h4>{{sub.sub_name.split(',')}}</h4>
    {% endfor %}
{% endfor %}
{% include 'footer.jinja' %}